### ISSUE TITLE
Wyze Video Doorbell Support

### ISSUE THREAD

**Issue by krystiancharubin** [kroo/wyzecam#12]
## 🔬 How To Reproduce

1. Run sample code

```bash
python3 wyze.py 
AV Client Start: chan_id=0 expected_chan=0 pn_serv_type=16
Sending response: <K10002ConnectAuth code=10002 resp_code=10003>
^CTraceback (most recent call last):
  File "wyze.py", line 51, in <module>
    main()
  File "wyze.py", line 27, in main
    with wyze_iotc.connect_and_auth(account, cam) as sess:
  File "/home/kcharubin/.local/lib/python3.8/site-packages/wyzecam/iotc.py", line 322, in __enter__
    self._auth()
  File "/home/kcharubin/.local/lib/python3.8/site-packages/wyzecam/iotc.py", line 295, in _auth
    mux.waitfor(resolving)
  File "/home/kcharubin/.local/lib/python3.8/site-packages/wyzecam/tutk/tutk_ioctl_mux.py", line 250, in waitfor
    time.sleep(0.1)
KeyboardInterrupt
```

### Environment

* OS: [e.g. Linux / Windows / macOS] Linux
* Python version, get it with: Python 3.8.5

```bash
python --version
```

## 📈 Expected behavior

Expect to see the video stream just like with v2 camera

**Comment by kroo** [comment]
Interesting!  I need to get a video doorbell to see what they're doing differently; stay tuned.

**Comment by kroo** [comment]
Will do!  I think it would be hard to reverse engineer remotely, so I just ordered one from Home Depot (after spending a couple hours in the store this morning trying to track down the "8 in inventory"!).  Should arrive Tuesday.

**Comment by kroo** [comment]
@krystiancharubin got this working!  pushing out release 1.2.0 now, with doorbell cam support.
