### ISSUE TITLE
Could this be added to HACS?

### ISSUE THREAD

**Issue by ikrowni** [kroo/wyzecam#58]
Could this be loaded as an addon within home assistant through HACS?

**Comment by kroo** [comment]
You would need to build a plugin specifically for home assistant (using this library behind the scenes), but yes, its definitely possible!

**Comment by ikrowni** [comment]
Well if it's okay with you and you hadn't already planned to make one do you mind if I put in a feature request over there for it?

**Comment by kroo** [comment]
Before you do, check out the solution people have landed on in #56 -- already supports Home assistant and homebridge by leveraging Frigate.

**Comment by ikrowni** [comment]
Doesn't seem as though it would work for a hassOS user though. I'm really gonna need 5o switch over to docker at some point. Feels like I miss out on something because of that at least monthly.

**Comment by mrlt8** [comment]
Not HACS, but I made a [Home Assistant add-on](https://github.com/mrlt8/docker-wyze-bridge/wiki/Home-Assistant) that should work with HassOS.

**Comment by ikrowni** [comment]
> Not HACS, but I made a [Home Assistant add-on](https://github.com/mrlt8/docker-wyze-bridge/wiki/Home-Assistant) that should work with HassOS.

Awesome thank you! How would I do the two-factor auth with this method?

**Comment by mrlt8** [comment]
The easiest way would be to use the [samba add-on](https://www.home-assistant.io/common-tasks/os/#installing-and-using-the-samba-add-on) and add your code to `/config/wyze-bridge/mfa_token.txt`

**Comment by ikrowni** [comment]
Oh I meant how do I get the token.

**Comment by ikrowni** [comment]
I noticed i cant run this at the same time as frigate since they both have the same port 1935 but i cant seem to change the port number through the configs panel either.

**Comment by mrlt8** [comment]
Don't know why, but the setting in Home Assistant seem to get "stuck" every now and then. Try stopping the add-on and hitting save a couple of times till the changes stick.

**Comment by ikrowni** [comment]
This worked. Had to do it like 6 times to get it to stick. The 2fa wouldn't stick for me no matter how many times I tried. I just put the 2fa auth code in the text file you stated and then I start the add-on before the code expires but the code gets removed from the txt file and an error pops up saying it needs auth.

I turned 2fa off for now but any pointers would be great. Thanks for the help

**Comment by mrlt8** [comment]
Yup, the txt file gets cleared on startup or after it gets used since it's a one-time-password. 

You need to start up the container and enter the code when you receive the sms or are prompted to for the TOTP.

**Comment by ikrowni** [comment]
> Yup, the txt file gets cleared on startup or after it gets used since it's a one-time-password.
> 
> You need to start up the container and enter the code when you receive the sms or are prompted to for the TOTP.

Okay so i started the container and it gives me this in the logs

```
2021/09/13 03:19:16 [MainThread] ☁️ Fetching 'auth' from the Wyze API...
2021/09/13 03:19:16 [MainThread] ⚠️ Error getting auth - Expired token?
2021/09/13 03:19:16 [MainThread] ♻️ Refresh auth tokens
```

So i go into my authenticator app and put that code into the mfa_token.txt file and save the file before the token expires.

But then it just keeps on giving me this over and over

```
2021/09/13 03:19:16 [MainThread] ☁️ Fetching 'auth' from the Wyze API...
2021/09/13 03:19:16 [MainThread] ⚠️ Error getting auth - Expired token?
2021/09/13 03:19:16 [MainThread] ♻️ Refresh auth tokens
```

**Comment by ikrowni** [comment]
nevermind i got it to work i think i had to delete the 3 files it created first im not sure what i did that was different.
