### ISSUE TITLE
WyzeIOTCSession - IOTC_ER_NOT_INITIALIZED

### ISSUE THREAD

**Issue by mrlt8** [kroo/wyzecam#66]
## 🐛 Bug Report

Hello, I'm trying to adjust the bitrate/frame size via WyzeIOTCSession as listed in the [documentation](https://kroo.github.io/wyzecam/reference/iotc_session/), however, I keep getting *IOTC_ER_NOT_INITIALIZED* whenever I try to use `WyzeIOTCSession`.

## 🔬 How To Reproduce

```python
import os
import wyzecam

auth_info = wyzecam.login(os.environ["WYZE_EMAIL"], os.environ["WYZE_PASSWORD"])
account = wyzecam.get_user_info(auth_info)
camera = wyzecam.get_camera_list(auth_info)[0]

with wyzecam.iotc.WyzeIOTCSession(wyzecam.tutk.tutk.load_library(),account,camera) as w:
	print(w.state)
```

### Environment

* OS: macOS 11.4
* Python version:  3.8.9

## 📈 Expected behavior

`WyzeIOTCSessionState.AUTHENTICATION_SUCCEEDED`

**Comment by kroo** [comment]
Hey there!  I saw you closed the issue, were you able to figure out what was happening?

**Comment by mrlt8** [comment]
yes, I was able to resolve it by calling iotc_initialize and av_initialize.
