### ISSUE TITLE
Is basicInfo wifidb actually link quality?

### ISSUE THREAD

**Issue by mrlt8** [kroo/wyzecam#72]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/kroo/wyzecam/issues?q=is%3Aissue).

## ❓ Question

I had assumed that basicInfo.wifidb represented rssi, but it seems to more related to link quality..? 
Any additional info would be appreciated!

## 📎 Additional context
```python
with wyzecam.WyzeIOTC() as wyze_iotc:
  with wyze_iotc.connect_and_auth(account, camera) as sess:
    print(sess.camera.camera_info['basicInfo']['wifidb'])
```

**Comment by kroo** [comment]
Good question, I haven't traced it all the way through the app, but I believe it's whats used on the Settings -> Device Info page (as little 'signal strength' indicator)...
