### ISSUE TITLE
Doorbell + Chime Integration

### ISSUE THREAD

**Issue by xcgt** [kroo/wyzecam#90]
## Checklist

- '[x]' I've searched the project's [`issues`](https://github.com/kroo/wyzecam/issues?q=is%3Aissue).

## ❓ Question

Is it possible to use this with the Wyze Doorbell + Chime? Will it also integrate with Home Assistant?

**Comment by kroo** [comment]
@xcgt i can confirm the Wyze video doorbell works.  I haven't seen a drop-in plugin built for home assistant with this yet, but it's certainly possible!
